# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_skipped: lowlighter
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_notable: yes
          plugin_notable_repositories: yes
          config_order: base.header, isocalendar, languages, notable, topics
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 7                                   # Display last week stats
          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                 # Wakatime url endpoint
          plugin_wakatime_user: .user.login                         # User
